services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: tareas-pt-app
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=tareas_pt
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

  webserver:
    image: nginx:1.25.3
    container_name: tareas-pt-webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.6
    container_name: tareas-pt-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=tareas_pt
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root_password
    volumes:
      - ./docker/db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tareas-pt-phpmyadmin
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8081:80"