version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html

  mariadb:
    build:
      context: ./docker/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: ci4_db
      MARIADB_USER: ci4_user
      MARIADB_PASSWORD: ci4_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: